version: "3.7"
services:
  web:
    build:
      context: ./
      dockerfile: "./docker/NextServer/Dockerfile"
    container_name: next-container
    restart: always
    #    volumes:
    #      - ./website:/var/www/html
    ports:
      - "81:3000"
